basePath: /v1
definitions:
  entity.Asset:
    properties:
      amount:
        type: number
      name:
        type: string
    type: object
  entity.Wallet:
    properties:
      address:
        type: string
      assets:
        items:
          $ref: '#/definitions/entity.Asset'
        type: array
      id:
        type: integer
      network:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: detail
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: Wallet Management
  title: Wallet Management Service
  version: "1.0"
paths:
  /wallets:
    post:
      consumes:
      - application/json
      description: Add a new wallet to the database
      operationId: create-wallet
      parameters:
      - description: Wallet details
        in: body
        name: wallet
        required: true
        schema:
          $ref: '#/definitions/entity.Wallet'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create a new wallet
      tags:
      - wallets
  /wallets/{id}:
    delete:
      consumes:
      - application/json
      description: Remove a specific wallet from the database
      operationId: delete-wallet
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Delete a wallet by ID
      tags:
      - wallets
    get:
      consumes:
      - application/json
      description: Get details of a specific wallet by its ID
      operationId: get-wallet-by-id
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Wallet'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Retrieve a wallet by ID
      tags:
      - wallets
swagger: "2.0"
