basePath: /v1
definitions:
  entity.TransactionRequest:
    properties:
      amount:
        description: Transaction amount
        type: number
      asset_name:
        description: Asset being transacted (e.g., BTC, ETH)
        type: string
      wallet_id:
        description: Wallet performing the transaction
        type: integer
    required:
    - amount
    - asset_name
    - wallet_id
    type: object
  entity.TransferRequest:
    properties:
      amount:
        description: Transfer amount
        type: number
      asset_name:
        description: Asset being transferred
        type: string
      execute_time:
        description: time (Unix) When this should be executed
        type: integer
      from_wallet_id:
        description: Sender wallet
        type: integer
      to_wallet_id:
        description: Receiver wallet
        type: integer
    required:
    - amount
    - asset_name
    - execute_time
    - from_wallet_id
    - to_wallet_id
    type: object
  v1.assetResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Asset Management Service (Command API - Writes to Kafka)
  title: Asset Management Service
  version: "1.0"
paths:
  /assets/deposit:
    post:
      consumes:
      - application/json
      description: Deposit funds into a wallet
      operationId: deposit
      parameters:
      - description: Deposit request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.assetResponse'
      summary: Deposit funds
      tags:
      - assets
  /assets/transfer:
    post:
      consumes:
      - application/json
      description: Transfer funds between wallets
      operationId: transfer
      parameters:
      - description: Transfer request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.assetResponse'
      summary: Transfer funds
      tags:
      - assets
  /assets/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw funds from a wallet
      operationId: withdraw
      parameters:
      - description: Withdraw request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.assetResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.assetResponse'
      summary: Withdraw funds
      tags:
      - assets
swagger: "2.0"
