app:
  name: 'message-sender'
  version: '1.0.0'

http:
  port: '8080'


logger:
  log_level: 'trace'
  rollbar_env: 'message-sender'


postgres:
  pool_max: 5
  url: 'postgres://user:pass@127.0.0.1:5432/postgres'

kafka:
   KAFKA_BROKER: 'kafka:9092'
   EVENT_TOPIC: 'event-journal'

