app:
  name: 'message-sender'
  version: '1.0.0'

http:
  port: '8080'


logger:
  log_level: 'trace'
  rollbar_env: 'message-sender'


postgres:
  pool_max: 5
  url: 'postgres://query_user:query_password@127.0.0.1:5433/query_db'
 

kafka:
  KAFKA_BROKER: '127.0.0.1:9092'
  EVENT_TOPIC: 'event-journal'