basePath: /v1
definitions:
  entity.Transaction:
    properties:
      amount:
        description: Transaction amount
        type: number
      asset_name:
        type: string
      created_at:
        description: Timestamp when the transaction occurred
        type: string
      id:
        description: Unique transaction ID
        type: integer
      target_wallet_id:
        description: For transfer transactions
        type: integer
      type:
        description: '"withdraw", "deposit", or "transfer"'
        type: string
      wallet_id:
        description: Wallet associated with the transaction
        type: integer
    type: object
  entity.WalletAsset:
    properties:
      amount:
        description: The amount of the asset
        type: number
      asset_name:
        description: The name of the asset (e.g., BTC, ETH)
        type: string
      updated_at:
        description: Timestamp of the last update
        type: string
      wallet_id:
        description: The ID of the wallet
        type: integer
    type: object
  v1.AssetBalanceResponse:
    properties:
      amount:
        type: number
      asset_name:
        type: string
      error:
        type: string
      status:
        type: string
      wallet_id:
        type: integer
    type: object
  v1.AssetResponse:
    properties:
      assets:
        items:
          $ref: '#/definitions/entity.WalletAsset'
        type: array
      error:
        type: string
      status:
        type: string
    type: object
  v1.TransactionHistoryResponse:
    properties:
      count:
        type: integer
      error:
        type: string
      status:
        type: string
      transactions:
        items:
          $ref: '#/definitions/entity.Transaction'
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: detail
        type: string
    type: object
host: localhost:8083
info:
  contact: {}
  description: Asset Query Service
  title: Asset Query Service
  version: "1.0"
paths:
  /wallets/{id}/assets:
    get:
      consumes:
      - application/json
      description: Get all assets for a specific wallet by its ID
      operationId: get-all-assets
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.AssetResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Retrieve all assets of a wallet
      tags:
      - wallets
  /wallets/{id}/assets/{asset}:
    get:
      consumes:
      - application/json
      description: Get the balance of a specific asset in a wallet
      operationId: get-asset-balance
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      - description: Asset Name
        in: path
        name: asset
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.AssetBalanceResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Retrieve balance of a specific asset
      tags:
      - wallets
  /wallets/{id}/transactions:
    get:
      consumes:
      - application/json
      description: Get the transaction history for a wallet
      operationId: get-transaction-history
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.TransactionHistoryResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Retrieve transaction history
      tags:
      - wallets
swagger: "2.0"
